# Generated by Django 4.0.4 on 2022-05-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('company', 'Company')], max_length=10),
        ),
    ]
